version: "3"

services:
  master:
    build:
      context: master
      dockerfile: dockerfile.master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123
      REPLICA_USER: replica
      REPLICA_USER_PASSWORD: 123
      REPLICATION_SLOT: slave1
    ports:
      - "5432:5432"